# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "KKid.xcworkspace",
    					scheme: "KKidUITests",
    					only_testing: "KKidUITests/KKidTakeScreenshots")
    frameit
    sh('find ./screenshots/en-US/ -type f \! -name "*framed*.png" -delete')
  	if !is_ci
  		notification(subtitle: "Finished Screenshots", message: "Fastlane has finished gathering screenshots for KKid", title: "fastlane: KKid", content_image: "https://api.kumpeapps.com/images/kumpeapps/base_logo_white_background.png")
  	end
  end

  desc "Build and upload beta version to testflight"
  lane :beta do
    if is_ci
		setup_ci
  		app_store_connect_api_key(
     		"key_id": ENV['APPLE_APP_STORE_API_KEY_ID'],
     		"issuer_id": ENV['APPLE_APPSTORE_API_ISSUER_ID'],
     		"key_content": ENV['APPLE_APP_STORE_API_KEY']
   		)
	end
  	increment_build_number
  	if is_ci
  		add_badge(dark: true)
  	end
  	build_app(scheme: "KKid", workspace: "KKid.xcworkspace")
  	upload_to_testflight(distribute_external: true, groups: "Public Testers", submit_beta_review: true, changelog: "Bug Fixes and New Features")
  end

  desc "Build and upload alpha version to testflight"
  lane :alpha do
    if is_ci
    setup_ci
      app_store_connect_api_key(
        "key_id": ENV['APPLE_APP_STORE_API_KEY_ID'],
        "issuer_id": ENV['APPLE_APPSTORE_API_ISSUER_ID'],
        "key_content": ENV['APPLE_APP_STORE_API_KEY']
      )
  end
    increment_build_number
    if is_ci
      add_badge(dark: true, alpha: true)
    end
    build_app(scheme: "KKid", workspace: "KKid.xcworkspace")
    upload_to_testflight(skip_waiting_for_build_processing: true, changelog: "Bug Fixes and New Features (Alpha Version)")
  end

  desc "Build and upload release version to Apple"
  lane :release do
    if is_ci
		setup_ci
  		app_store_connect_api_key(
     		"key_id": ENV['APPLE_APP_STORE_API_KEY_ID'],
     		"issuer_id": ENV['APPLE_APPSTORE_API_ISSUER_ID'],
     		"key_content": ENV['APPLE_APP_STORE_API_KEY']
   		)
	end
  	run_tests(workspace: "KKid.xcworkspace",
            devices: ["iPhone 12 Pro"],
            scheme: "KKidUITests",
            only_testing: "KKidUITests/KKidUITests")
  	increment_build_number
  	build_app(scheme: "KKid", workspace: "KKid.xcworkspace")
  	deliver(
  		force: true,
  		metadata_path: "./fastlane/metadata",
  		submit_for_review: false,
    	automatic_release: true,
      overwrite_screenshots: true,
      expire_previous_builds: true
  	)
  	if !is_ci
  		notification(subtitle: "Finished Uploading", message: "KKid release build upload complete", title: "fastlane: KKid", content_image: "https://api.kumpeapps.com/images/kumpeapps/base_logo_white_background.png")
  	end
  end

  lane :test do
  	run_tests(workspace: "KKid.xcworkspace",
            devices: ["iPhone 12 Pro","iPad Pro (12.9-inch) (3rd generation)"],
            scheme: "KKidUITests",
            only_testing: "KKidUITests/KKidUITests")
  	if !is_ci
  		notification(subtitle: "KKid Tests Complete", message: "KKid testing complete", title: "fastlane: KKid", content_image: "https://api.kumpeapps.com/images/kumpeapps/base_logo_white_background.png")
  	end
  end

  lane :matchget do
	if is_ci
		setup_ci
	end
	match(type: "appstore", readonly: is_ci, git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'], git_url: "https://github.com/kumpeapps/fastlane_certs.git")
  end

  lane :notifytest do

  	if !is_ci
  		notification(subtitle: "Finished Uploading", message: "KKid release build upload complete", title: "fastlane: KKid", content_image: "https://api.kumpeapps.com/images/kumpeapps/base_logo_white_background.png")
  	end
  end

end
